// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	usercenter "github/community-online/app/usercenter/cmd/api/internal/handler/usercenter"
	"github/community-online/app/usercenter/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: usercenter.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: usercenter.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/wxmini-auth",
				Handler: usercenter.WxMiniAuthHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/messagecode",
				Handler: usercenter.MessagecodeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/get-captcha",
				Handler: usercenter.GetCaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/verfy-captcha",
				Handler: usercenter.VerfyCaptchaHandler(serverCtx),
			},
		},
		rest.WithPrefix("/usercenter/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/detail",
				Handler: usercenter.DetailHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/usercenter/v1"),
	)
}
