// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	usercenter "github/community-online/app/usercenter/cmd/api/internal/handler/usercenter"
	"github/community-online/app/usercenter/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: usercenter.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: usercenter.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/wxmini-auth",
				Handler: usercenter.WxMiniAuthHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/messagecode",
				Handler: usercenter.MessagecodeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/get-captcha",
				Handler: usercenter.GetCaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/verfy-captcha",
				Handler: usercenter.VerfyCaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/change-pwd",
				Handler: usercenter.ChangePwdHandler(serverCtx),
			},
		},
		rest.WithPrefix("/usercenter/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.OnlineStatus},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/user/detail",
					Handler: usercenter.DetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/update-user",
					Handler: usercenter.UpdateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/delete-user",
					Handler: usercenter.DeleteUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/online-user",
					Handler: usercenter.GetOnlineUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/usercenter/v1"),
	)
}
