// Code generated by goctl. DO NOT EDIT!
// Source: sms.proto

package server

import (
	"context"

	"github/community-online/app/sms/cmd/rpc/internal/logic"
	"github/community-online/app/sms/cmd/rpc/internal/svc"
	"github/community-online/app/sms/cmd/rpc/pb"
)

type SmsServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSmsServer
}

func NewSmsServer(svcCtx *svc.ServiceContext) *SmsServer {
	return &SmsServer{
		svcCtx: svcCtx,
	}
}

func (s *SmsServer) GetMsgCode(ctx context.Context, in *pb.GetMsgCodeReq) (*pb.GetMsgCodeResp, error) {
	l := logic.NewGetMsgCodeLogic(ctx, s.svcCtx)
	return l.GetMsgCode(in)
}
