// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
	Info     string `json:"info"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile"`
	Msgcode  string `json:"msgcode"`
	Password string `json:"password"`
	Nickname string `json:"nickname,optional"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type MsgCodeReq struct {
	MsgType string `json:"msgType"`
	Mobile  string `json:"mobile"`
}

type MsgLoginReq struct {
	Mobile  string `json:"mobile"`
	Msgcode string `json:"msgcode"`
}

type MsgLoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type WXMiniAuthReq struct {
	Code          string `json:"code"`
	PhoneCode     string `json:"phoneCode,optional"`
	IV            string `json:"iv,optional"`
	EncryptedData string `json:"encryptedData,optional"`
}

type WXMiniAuthResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserInfo User `json:"userInfo"`
}

type GetCaptchaReq struct {
}

type GetCaptchaResp struct {
	ImageBase64 string `json:"imageBase64"`
	ThumbBase64 string `json:"thumbBase64"`
	CaptchaKey  string `json:"captchaKey"`
}

type VerfyCaptchaReq struct {
	Dots       []int64 `json:"dots"`
	CaptchaKey string  `json:"captchaKey"`
}

type VerfyCaptchaResp struct {
	Result bool `json:"result"`
}
